openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Wallet Controller
    description: Управление операциями над кошельком
paths:
  /api/v1/wallets/{uuid}/withdraw:
    post:
      tags:
        - Wallet Controller
      summary: Перевести деньги на другой кошелёк по его ID
      operationId: withdrawOperation
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferOperationRequest'
        required: true
      responses:
        '200':
          description: Перевод выполнен успешно!
          content:
            application/json:
              examples:
                200 OK:
                  description: 200 OK
                  value:
                    operationType: DEPOSIT
                    oldBalanceFrom: 1000
                    newBalanceFrom: 1500
                    operationTime: '2025-11-17T10:25:00'
        '400':
          description: Некорректный запрос!
          content:
            application/json:
              examples:
                400 Bad Request:
                  description: 400 Bad Request
                  value:
                    title: Validation Error
                    status: 400
                    details: Request validation failed
                    instance: >-
                      /api/v1/wallets/123e4567-e89b-12d3-a456-426614174000/deposit
                    localDateTime: '2025-11-17T10:30:00'
                    fieldError:
                      - field: amount
                        message: Amount must be greater than zero
        '500':
          description: Неизвестная ошибка!
          content:
            application/json:
              examples:
                500 Internal Server Error:
                  description: 500 Internal Server Error
                  value:
                    title: Internal Server Error
                    status: 500
                    details: Unexpected error occurred
                    instance: /api/v1/wallets/123/deposit
                    localDateTime: '2025-11-16T21:10:00'
  /api/v1/wallets/{uuid}/deposit:
    post:
      tags:
        - Wallet Controller
      summary: Внести деньги на кошелёк по его ID
      operationId: depositOperation
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositOperationRequest'
        required: true
      responses:
        '200':
          description: Пополнение прошло успешно!
          content:
            application/json:
              examples:
                200 OK:
                  description: 200 OK
                  value:
                    operationType: DEPOSIT
                    oldBalanceFrom: 1000
                    newBalanceFrom: 1500
                    operationTime: '2025-11-17T10:25:00'
        '400':
          description: Некорректный запрос!
          content:
            application/json:
              examples:
                400 Bad Request:
                  description: 400 Bad Request
                  value:
                    title: Validation Error
                    status: 400
                    details: Request validation failed
                    instance: >-
                      /api/v1/wallets/123e4567-e89b-12d3-a456-426614174000/deposit
                    localDateTime: '2025-11-17T10:30:00'
                    fieldError:
                      - field: amount
                        message: Amount must be greater than zero
        '500':
          description: Неизвестная ошибка!
          content:
            application/json:
              examples:
                500 Internal Server Error:
                  description: 500 Internal Server Error
                  value:
                    title: Internal Server Error
                    status: 500
                    details: Unexpected error occurred
                    instance: /api/v1/wallets/123/deposit
                    localDateTime: '2025-11-16T21:10:00'
  /api/v1/wallets:
    get:
      tags:
        - Wallet Controller
      summary: Получить список всех кошельков
      operationId: findAll
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: Баланс получен успешно!
          content:
            application/json:
              examples:
                200 OK:
                  description: 200 OK
                  value:
                    - walletID: 11111111-1111-1111-1111-111111111111
                      balance: 4431
                      requestedAt: '2025-11-17 11:04:02'
                    - walletID: 22222222-2222-2222-2222-222222222222
                      balance: 1268
                      requestedAt: '2025-11-17 11:04:02'
                    - walletID: 33333333-3333-3333-3333-333333333333
                      balance: 184
                      requestedAt: '2025-11-17 11:04:02'
  /api/v1/wallets/{uuid}:
    get:
      tags:
        - Wallet Controller
      summary: Получить текущий баланс кошелька
      operationId: getWalletBalance
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Баланс получен успешно!
          content:
            application/json:
              examples:
                200 OK:
                  description: 200 OK
                  value: |
                    {
                      "walletID": "1234-56789-1234-58789-5325321664"
                      "balance": 1250.75,
                      "requestedAt": "2025-11-17T10:15:30"
                    }
        '400':
          description: Некорректный запрос!
          content:
            application/json:
              examples:
                400 Bad Request:
                  description: 400 Bad Request
                  value:
                    title: Bad Request
                    status: 400
                    details: Invalid wallet UUID format
                    instance: /api/v1/wallets/invalid-uuid
                    localDateTime: '2025-11-17T10:20:00'
                    fieldError: []
        '500':
          description: Неизвестная ошибка!
          content:
            application/json:
              examples:
                500 Internal Server Error:
                  description: 500 Internal Server Error
                  value:
                    title: Internal Server Error
                    status: 500
                    details: Unexpected error occurred
                    instance: /api/v1/wallets/123/deposit
                    localDateTime: '2025-11-16T21:10:00'
components:
  schemas:
    TransferOperationRequest:
      required:
        - amount
        - walletIDTo
      type: object
      properties:
        walletIDTo:
          type: string
          format: uuid
        amount:
          type: number
    DepositOperationRequest:
      required:
        - amount
      type: object
      properties:
        amount:
          type: number
